# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Number Guesser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Number Guesser
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/MLModelInterpreter'
pod 'SwiftyJSON'
pod 'Alamofire'

end
